-- ============================================================
-- RAFIKOSAN lemillion project — Supabase PostgreSQL Schema
-- ============================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─── pengaturan (settings) ───────────────────────────────────
CREATE TABLE IF NOT EXISTS pengaturan (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kunci_pengaturan TEXT NOT NULL UNIQUE,
  nilai       TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Default prices
INSERT INTO pengaturan (kunci_pengaturan, nilai) VALUES
  ('harga_utama',    '17000'),
  ('harga_ekstensi', '7000')
ON CONFLICT (kunci_pengaturan) DO NOTHING;

-- ─── admin ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS admin (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  nama_lengkap  TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── kode_akses ──────────────────────────────────────────────
CREATE TYPE jenis_kode_enum AS ENUM ('utama', 'ekstensi');

CREATE TABLE IF NOT EXISTS kode_akses (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode        TEXT NOT NULL UNIQUE,
  jenis_kode  jenis_kode_enum NOT NULL,
  is_aktif    BOOLEAN NOT NULL DEFAULT TRUE,
  is_digunakan BOOLEAN NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  used_at     TIMESTAMPTZ
);

-- ─── sesi ────────────────────────────────────────────────────
CREATE TYPE status_sesi_enum AS ENUM ('aktif', 'ekstensi', 'pilih_frame', 'selesai');

CREATE TABLE IF NOT EXISTS sesi (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode_sesi   UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  waktu_mulai TIMESTAMPTZ,
  waktu_selesai TIMESTAMPTZ,
  status      status_sesi_enum NOT NULL DEFAULT 'aktif',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── transaksi ───────────────────────────────────────────────
CREATE TYPE jenis_bayar_enum AS ENUM ('qris', 'kode_akses');
CREATE TYPE tujuan_enum AS ENUM ('utama', 'ekstensi');
CREATE TYPE status_bayar_enum AS ENUM ('pending', 'sukses', 'gagal');

CREATE TABLE IF NOT EXISTS transaksi (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sesi     BIGINT NOT NULL REFERENCES sesi(id) ON DELETE CASCADE,
  jenis_bayar jenis_bayar_enum NOT NULL,
  id_kode     BIGINT REFERENCES kode_akses(id) ON DELETE SET NULL,
  tujuan      tujuan_enum NOT NULL,
  status_bayar status_bayar_enum NOT NULL DEFAULT 'pending',
  jumlah      INTEGER,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── foto ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS foto (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sesi     BIGINT NOT NULL REFERENCES sesi(id) ON DELETE CASCADE,
  path_file   TEXT NOT NULL,
  waktu_jepret TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── master_frame ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS master_frame (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_frame    TEXT NOT NULL,
  file_template TEXT NOT NULL,
  kapasitas     INTEGER NOT NULL DEFAULT 6,
  layout_cols   INTEGER NOT NULL DEFAULT 2,
  layout_rows   INTEGER NOT NULL DEFAULT 3,
  is_aktif      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Default frames
INSERT INTO master_frame (nama_frame, file_template, kapasitas, layout_cols, layout_rows) VALUES
  ('Portrait 2x3', '/frames/portrait-2x3.png', 6, 2, 3),
  ('Landscape 3x2', '/frames/landscape-3x2.png', 6, 3, 2)
ON CONFLICT DO NOTHING;

-- ─── hasil_frame ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS hasil_frame (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sesi     BIGINT NOT NULL REFERENCES sesi(id) ON DELETE CASCADE,
  id_frame    BIGINT NOT NULL REFERENCES master_frame(id),
  path_hasil  TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── foto_terpilih ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS foto_terpilih (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_hasil_frame  BIGINT NOT NULL REFERENCES hasil_frame(id) ON DELETE CASCADE,
  id_foto         BIGINT NOT NULL REFERENCES foto(id) ON DELETE CASCADE,
  urutan_posisi   INTEGER NOT NULL CHECK (urutan_posisi BETWEEN 1 AND 6),
  UNIQUE (id_hasil_frame, urutan_posisi)
);

-- ─── RLS Policies (optional, adapt as needed) ─────────────────
ALTER TABLE pengaturan ENABLE ROW LEVEL SECURITY;
ALTER TABLE kode_akses ENABLE ROW LEVEL SECURITY;
ALTER TABLE sesi ENABLE ROW LEVEL SECURITY;
ALTER TABLE transaksi ENABLE ROW LEVEL SECURITY;
ALTER TABLE foto ENABLE ROW LEVEL SECURITY;
ALTER TABLE master_frame ENABLE ROW LEVEL SECURITY;
ALTER TABLE hasil_frame ENABLE ROW LEVEL SECURITY;
ALTER TABLE foto_terpilih ENABLE ROW LEVEL SECURITY;

-- Public read for pengaturan (for price display)
CREATE POLICY "Public read pengaturan" ON pengaturan FOR SELECT USING (true);
-- Public read for master_frame
CREATE POLICY "Public read master_frame" ON master_frame FOR SELECT USING (is_aktif = true);
-- Anon can insert/read sesi, transaksi, foto, hasil_frame, foto_terpilih, kode_akses
CREATE POLICY "Anon sesi all"         ON sesi         FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Anon transaksi all"    ON transaksi     FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Anon foto all"         ON foto          FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Anon hasil_frame all"  ON hasil_frame   FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Anon foto_terpilih all" ON foto_terpilih FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Anon kode_akses read"  ON kode_akses    FOR SELECT USING (true);
CREATE POLICY "Anon kode_akses update" ON kode_akses   FOR UPDATE USING (true) WITH CHECK (true);

-- ─── Indexes ─────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_sesi_kode       ON sesi(kode_sesi);
CREATE INDEX IF NOT EXISTS idx_sesi_status     ON sesi(status);
CREATE INDEX IF NOT EXISTS idx_foto_sesi       ON foto(id_sesi);
CREATE INDEX IF NOT EXISTS idx_transaksi_sesi  ON transaksi(id_sesi);
CREATE INDEX IF NOT EXISTS idx_kode_akses_kode ON kode_akses(kode);
