[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS    = "--legacy-peer-deps"

[functions]
  directory      = ".netlify/functions-internal"
  node_bundler   = "esbuild"
  included_files = [".output/**"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options        = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/server"
  status = 200
